// Generated by CoffeeScript 1.10.0
(function() {
  var $, after, every, splitText;

  $ = jQuery;

  splitText = function(str, pos) {
    return [str.substring(0, pos), str.substring(pos)];
  };

  after = function(ms, fn) {
    return setTimeout(fn, ms);
  };

  every = function(ms, fn) {
    return setInterval(fn, ms);
  };

  window.init = function(mp3Url, spanPrefix) {
    $(document).ready(function() {
      return $('body').layout({
        enableCursorHotkey: false,
        north__size: 42,
        north__spacing_open: 0
      });
    });
    return initMp3(mp3Url, function(sound) {
      var curTime, duration, lastPosition;
      window.mySound = sound;
      window.transcript = new Transcript(sound, spanPrefix, 'highlightMouseover', 'highlightPlaying');
      curTime = document.getElementById('curTime');
      duration = formatTime(sound.getDuration());
      lastPosition = -1;
      every(100, function() {
        var millis;
        millis = sound.getPosition();
        if (lastPosition !== millis) {
          curTime.innerHTML = formatTime(millis) + ' <span class="muted">/ ' + duration + '</span>';
          return lastPosition = millis;
        }
      });
      $('#playButton').click(function() {
        return sound.togglePause();
      });
      shortcut.add('Space', function() {
        return sound.togglePause();
      });
      return $('#loadingAudioAlert').remove();
    });
  };

}).call(this);
